services:

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    labels:
      - homepage.group=Infra
      - homepage.name=Portainer
      - homepage.icon=portainer.svg
      - homepage.href=https://${RASPBERRY_ADDRESS}:9443
      - homepage.description=Docker Management
    ports:
      - 9443:9443
    volumes:
      - ${DOCKER_DIR}/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: always
    labels:
      - homepage.group=Infra
      - homepage.name=Traefik
      - homepage.icon=traefik.svg
      - homepage.href=${RASPBERRY_ADDRESS}:8081
      - homepage.description=Docker Reverse Proxy
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
      - "--experimental.plugins.fail2ban.modulename=github.com/tomMoulard/fail2ban"
      - "--experimental.plugins.fail2ban.version=v0.8.9"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - ${DOCKER_DIR}/traefik/data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - infra_default
      - media_infra_net
      - apps_infra_net

  homepage:
      image: ghcr.io/gethomepage/homepage:latest
      container_name: homepage
      restart: unless-stopped
      user: root
      environment:
        - HOMEPAGE_ALLOWED_HOSTS=${RASPBERRY_IP}:3001
      volumes:
        # Pasta onde ficarão as configurações do painel
        - ../homepage/config:/app/config 
        # Necessário para ele "ler" os outros containers do Docker
        - /var/run/docker.sock:/var/run/docker.sock:ro 
      # Como você usa Traefik, não precisa abrir portas, basta colocar as labels do Traefik aqui:
      ports:
       - "3001:3000"
      networks:
        - infra_default
        - media_infra_net
        - apps_infra_net

networks:
  infra_default:
    external: true
  media_infra_net:
    external: true
  apps_infra_net:
    external: true
