services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.svg
      - homepage.href=${RASPBERRY_ADDRESS}:32400
      - homepage.description=Plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${GENERIC_TIMEZONE}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    group_add:
      - ${PGID}  # GID of 'drive' group
    volumes:
      - ${DOCKER_DIR}/plex/library:/config
      - /mnt/media/data/media:/data/media
      - /dev/shm:/transcode
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${GENERIC_TIMEZONE}
      - JELLYFIN_PublishedServerUrl=home.${DOMAIN_NAME}/jellyfin
    volumes:
      - ${DOCKER_DIR}/jellyfin/config:/config
      - ${DOCKER_DIR}/jellyfin/spotlight/:/usr/share/jellyfin/web/UI
      - /mnt/media/data/media:/data/media
      - /dev/shm:/transcode
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.svg
      - homepage.href=https://home.${DOMAIN_NAME}/jellyfin
      - homepage.description=Jellyfin
      - homepage.widget.type=jellyfin
      - homepage.widget.url=https://home.${DOMAIN_NAME}/jellyfin
      - homepage.widget.key=${JELLYFIN_API_KEY}
      - homepage.widget.version=1
      - homepage.widget.enableBlocks=true
      - homepage.widget.enableNowPlaying=true
      - homepage.widget.enableUser=true
      - homepage.widget.enableMediaControl=true
      - homepage.widget.showEpisodeNumber=true
      - homepage.widget.expandOneStreamToTwoRows=true

      - 'traefik.enable=true'

      # Primeiro Dominio
      - 'traefik.http.routers.jellyfin.entryPoints=websecure'
      - 'traefik.http.routers.jellyfin.rule=Host(`home.${DOMAIN_NAME}`) && PathPrefix(`/jellyfin`)'
      - 'traefik.http.routers.jellyfin.tls=true'
      - 'traefik.http.routers.jellyfin.tls.certResolver=mytlschallenge'
      - 'traefik.http.routers.jellyfin.tls.domains=home.${DOMAIN_NAME}'
      - 'traefik.http.routers.jellyfin.middlewares=jellyfin-mw,fail2ban-jellyfin@docker'

      # Segundo Domínio (.by)
      - 'traefik.http.routers.jellyfin-by.entryPoints=websecure'
      - 'traefik.http.routers.jellyfin-by.rule=Host(`home.${DOMAIN_NAME_NEW}`) && PathPrefix(`/jellyfin`)'
      - 'traefik.http.routers.jellyfin-by.tls=true'
      - 'traefik.http.routers.jellyfin-by.tls.certResolver=mytlschallenge'
      - 'traefik.http.routers.jellyfin-by.middlewares=jellyfin-mw,fail2ban-jellyfin@docker'
      - 'traefik.http.routers.jellyfin-by.service=jellyfin-svc'

      # Middlewares
      - 'traefik.http.middlewares.jellyfin-mw.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
      - 'traefik.http.middlewares.jellyfin-mw.headers.SSLRedirect=true'
      # - 'traefik.http.middlewares.jellyfin-mw.headers.SSLHost=home.${DOMAIN_NAME}'
      # - 'traefik.http.middlewares.jellyfin-mw.headers.SSLForceHost=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.STSSeconds=315360000'
      - 'traefik.http.middlewares.jellyfin-mw.headers.STSIncludeSubdomains=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.STSPreload=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.forceSTSHeader=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.contentTypeNosniff=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.customresponseheaders.X-XSS-PROTECTION=1'
      - "traefik.http.middlewares.jellyfin-mw.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.jellyfin-mw.headers.customResponseHeaders.Content-Security-Policy=frame-ancestors 'self' https://home.${DOMAIN_NAME} https://home.${DOMAIN_NAME_NEW}"

      ## HTTP Service
      - 'traefik.http.routers.jellyfin.service=jellyfin-svc'
      - 'traefik.http.services.jellyfin-svc.loadBalancer.server.port=8096'
      - 'traefik.http.services.jellyfin-svc.loadBalancer.passHostHeader=true'

      - 'traefik.http.routers.jellyfin-insecure.entryPoints=web'
      - 'traefik.http.routers.jellyfin-insecure.rule=(Host(`home.${DOMAIN_NAME}`) || Host(`home.${DOMAIN_NAME_NEW}`)) && PathPrefix(`/jellyfin`)'
      - 'traefik.http.routers.jellyfin-insecure.middlewares=jellyfin-insecure-mw,fail2ban-jellyfin@docker'

      - 'traefik.http.middlewares.jellyfin-insecure-mw.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.jellyfin-insecure-mw.redirectscheme.port=9999' # remove if you are using a default port
      - 'traefik.http.middlewares.jellyfin-insecure-mw.redirectscheme.permanent=false'
      - 'traefik.http.routers.jellyfin-insecure.service=noop@internal'
      ## Fail2Ban
      - traefik.http.middlewares.fail2ban-jellyfin.plugin.fail2ban.allowlist.ip=::1,127.0.0.1
      - traefik.http.middlewares.fail2ban-jellyfin.plugin.fail2ban.rules.bantime=10m
      - traefik.http.middlewares.fail2ban-jellyfin.plugin.fail2ban.rules.enabled=true
      - traefik.http.middlewares.fail2ban-jellyfin.plugin.fail2ban.rules.findtime=10m
      - traefik.http.middlewares.fail2ban-jellyfin.plugin.fail2ban.rules.maxretry=4
      - traefik.http.middlewares.fail2ban-jellyfin.plugin.fail2ban.rules.statuscode=401
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      - media_infra_net
    entrypoint: ['sh', '-c', '/usr/share/jellyfin/web/UI/install-spotlight.sh && exec /init']

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    labels:
      - homepage.group=Media
      - homepage.name=Jellyseerr
      - homepage.icon=jellyseerr.svg
      - homepage.href=https://discover.${DOMAIN_NAME}
      - homepage.description=User frienfly movie requester
      - homepage.widget.type=seerr
      - homepage.widget.url=https://discover.${DOMAIN_NAME}
      - homepage.widget.key=${SEERR_API_KEY}
      - homepage.widget.fields=["pending","approved","available","completed"]

      - traefik.enable=true
      - traefik.http.routers.jellyseerr.rule=Host(`discover.${DOMAIN_NAME}`)
      - traefik.http.routers.jellyseerr.tls=true
      - traefik.http.routers.jellyseerr.entrypoints=web,websecure
      - traefik.http.routers.jellyseerr.tls.certresolver=mytlschallenge

      # Segundo Domínio (.by)
      - traefik.http.routers.jellyseerr-by.rule=Host(`discover.${DOMAIN_NAME_NEW}`)
      - traefik.http.routers.jellyseerr-by.tls=true
      - traefik.http.routers.jellyseerr-by.entrypoints=web,websecure
      - traefik.http.routers.jellyseerr-by.tls.certResolver=mytlschallenge

      - traefik.http.middlewares.jellyseerr.headers.SSLRedirect=true
      - traefik.http.middlewares.jellyseerr.headers.STSSeconds=315360000
      - traefik.http.middlewares.jellyseerr.headers.browserXSSFilter=true
      - traefik.http.middlewares.jellyseerr.headers.contentTypeNosniff=true
      - traefik.http.middlewares.jellyseerr.headers.forceSTSHeader=true
      # - traefik.http.middlewares.jellyseerr.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.jellyseerr.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.jellyseerr.headers.STSPreload=true
      - traefik.http.middlewares.fail2ban-jellyseerr.plugin.fail2ban.allowlist.ip=::1,127.0.0.1
      - traefik.http.middlewares.fail2ban-jellyseerr.plugin.fail2ban.rules.bantime=10m
      - traefik.http.middlewares.fail2ban-jellyseerr.plugin.fail2ban.rules.enabled=true
      - traefik.http.middlewares.fail2ban-jellyseerr.plugin.fail2ban.rules.findtime=10m
      - traefik.http.middlewares.fail2ban-jellyseerr.plugin.fail2ban.rules.maxretry=4
      - traefik.http.middlewares.fail2ban-jellyseerr.plugin.fail2ban.rules.statuscode=401
      # - traefik.http.middlewares.f2b.plugin.fail2ban.rules.urlregexps[0].regexp=/api/v1/auth/me
      # - traefik.http.middlewares.f2b.plugin.fail2ban.rules.urlregexps[0].mode=allow
      - traefik.http.routers.jellyseerr.middlewares=jellyseerr@docker,fail2ban-jellyseerr@docker
    environment:
      - LOG_LEVEL=debug
      - TZ=${GENERIC_TIMEZONE}
    ports:
      - 5055:5055
    volumes:
      - ${DOCKER_DIR}/jellyseerr/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    depends_on:
      - jellyfin
    networks:
      - media_infra_net

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    labels:
      - homepage.group=Media
      - homepage.name=Radarr
      - homepage.icon=radarr.svg
      - homepage.href=${RASPBERRY_ADDRESS}:7878
      - homepage.description=Movie management
      - homepage.widget.type=radarr
      - homepage.widget.url=${RASPBERRY_ADDRESS}:7878
      - homepage.widget.key=${RADARR_API_KEY}
      - homepage.widget.fields=["wanted","missing","queued","movies"]
      - homepage.widget.enableQueue=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${GENERIC_TIMEZONE}
    volumes:
      - ${DOCKER_DIR}/radarr/data:/config
      - /mnt/media/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    labels:
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr.svg
      - homepage.href=${RASPBERRY_ADDRESS}:8989
      - homepage.description=Series management
      - homepage.widget.type=sonarr
      - homepage.widget.url=${RASPBERRY_ADDRESS}:8989
      - homepage.widget.key=${SONARR_API_KEY}
      - homepage.widget.fields=["wanted","queued","series"]
      - homepage.widget.enableQueue=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${GENERIC_TIMEZONE}
    volumes:
      - ${DOCKER_DIR}/sonarr/data:/config
      - /mnt/media/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    labels:
      - homepage.group=Media
      - homepage.name=Lidarr
      - homepage.icon=lidarr.svg
      - homepage.href=${RASPBERRY_ADDRESS}:8686
      - homepage.description=Music management
      - homepage.widget.type=lidarr
      - homepage.widget.url=${RASPBERRY_ADDRESS}:8686
      - homepage.widget.key=${LIDARR_API_KEY}
      - homepage.widget.fields=["wanted","queued","artists"]
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${GENERIC_TIMEZONE}
    volumes:
      - ${DOCKER_DIR}/lidarr/data:/config
      - /mnt/media/data:/data
    ports:
      - 8686:8686
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    labels:
      - homepage.group=Media
      - homepage.name=Bazarr
      - homepage.icon=bazarr.svg
      - homepage.href=${RASPBERRY_ADDRESS}:6767
      - homepage.description=Subtitle management
      - homepage.widget.type=bazarr
      - homepage.widget.url=${RASPBERRY_ADDRESS}:6767
      - homepage.widget.key=${BAZARR_API_KEY}
      - homepage.widget.fields=["missingEpisodes","missingMovies"]
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${GENERIC_TIMEZONE}
    volumes:
      - ${DOCKER_DIR}/bazarr/data:/config
      - /mnt/media/data/media:/data/media
    ports:
      - 6767:6767
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    labels:
      - homepage.group=Media
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.svg
      - homepage.href=${RASPBERRY_ADDRESS}:9696
      - homepage.description=Tracker management
      - homepage.widget.type=prowlarr
      - homepage.widget.url=${RASPBERRY_ADDRESS}:9696
      - homepage.widget.key=${PROWLARR_API_KEY}
      - homepage.widget.fields=["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs", "numberOfFailQueries"]
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${GENERIC_TIMEZONE}
    volumes:
      - ${DOCKER_DIR}/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:latest # or maintainerr/maintainerr:latest
    container_name: maintainerr
    labels:
      - homepage.group=Media
      - homepage.name=Maintainerr
      - homepage.icon=maintainerr.svg
      - homepage.href=${RASPBERRY_ADDRESS}:6246
      - homepage.description=Deletion automation and Collection management
      - homepage.widget.type=maintainerr
      - homepage.widget.url=${RASPBERRY_ADDRESS}:6246
    user: 1000:1000
    volumes:
      - ${DOCKER_DIR}/maintainerr/data:/opt/data
    environment:
      - TZ=${GENERIC_TIMEZONE}
#      - BASE_PATH=/maintainerr # uncomment if you're serving maintainerr from a subdirectory
#      - UI_HOSTNAME=:: # uncomment if you want to listen on IPv6 instead (default 0.0.0.0)
#      - UI_PORT=6247 # uncomment to change the UI port (default 6246)
#      - GITHUB_TOKEN=ghp_yourtoken # Optional: GitHub Personal Access Token for higher API rate limits (60/hr without, 5000/hr with token)
    ports:
      - 6246:6246
    restart: unless-stopped

  alternatrr:
    image: ghcr.io/soredake/alternatrr:latest
    platform: linux/amd64
    container_name: alternatrr
    labels:
      - homepage.group=Media
      - homepage.name=Alternatrr
      - homepage.icon=configarr.svg
      - homepage.href=${RASPBERRY_ADDRESS}:6247
      - homepage.description=Sonarr metadata management
    environment:
    - ConnectionStrings__DefaultConnection=Data Source=/opt/alternatrr/app/alternatrr.db
    - ConnectionStrings__sonarr=Data Source=/opt/sonarr/sonarr.db
    - Login__Username=${ALTERNATRR_LOGIN}
    - Login__Password=${ALTERNATRR_PW}
    # - VIRTUAL_HOST=alternatrr.YOURDOMAIN.COM
    # - VIRTUAL_PORT=80
    # - LETSENCRYPT_HOST=alternatrr.YOURDOMAIN.COM
    # - LETSENCRYPT_EMAIL=YOUREMAILADDRESS
    ports:
      - 6247:80
    volumes:
    - ${DOCKER_DIR}/sonarr/data:/opt/sonarr  #Mounting the directory with sonarr.db in it
    - ${DOCKER_DIR}/alternatrr/app:/opt/alternatrr/app #Mounting the alternatrr.db peristent login

  suwayomi_server:
    image: ghcr.io/suwayomi/suwayomi-server:latest
    container_name: suwayomi-server
    labels:
      - homepage.group=Media
      - homepage.name=Suwayomi Server
      - homepage.icon=suwayomi.svg
      - homepage.href=${RASPBERRY_ADDRESS}:4568
      - homepage.description=Manga management
    volumes: # The order matters! Make sure the downloads is first in the volume list or it will not work!
      - /mnt/media/data/suwayomi-server/downloads:/home/suwayomi/.local/share/Tachidesk/downloads
      - /mnt/media/data/suwayomi-server/files:/home/suwayomi/.local/share/Tachidesk
    ports:
      - 4568:4567
    restart: unless-stopped

  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    labels:
      - homepage.group=Media
      - homepage.name=Kavita
      - homepage.icon=kavita.svg
      - homepage.href=https://kavita.${DOMAIN_NAME}
      - homepage.description=Manga bookshelf

      - traefik.enable=true
      - traefik.http.routers.kavita.rule=Host(`kavita.${DOMAIN_NAME}`)
      - traefik.http.routers.kavita.tls=true
      - traefik.http.routers.kavita.entrypoints=web,websecure
      - traefik.http.routers.kavita.tls.certresolver=mytlschallenge

      # Segundo Domínio (.by)
      - traefik.http.routers.kavita-by.rule=Host(`kavita.${DOMAIN_NAME_NEW}`)
      - traefik.http.routers.kavita-by.tls=true
      - traefik.http.routers.kavita-by.entrypoints=web,websecure
      - traefik.http.routers.kavita-by.tls.certResolver=mytlschallenge

      - traefik.http.middlewares.kavita.headers.SSLRedirect=true
      - traefik.http.middlewares.kavita.headers.STSSeconds=315360000
      - traefik.http.middlewares.kavita.headers.browserXSSFilter=true
      - traefik.http.middlewares.kavita.headers.contentTypeNosniff=true
      - traefik.http.middlewares.kavita.headers.forceSTSHeader=true
      # - traefik.http.middlewares.jellyseerr.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.kavita.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.kavita.headers.STSPreload=true
      - traefik.http.middlewares.fail2ban-kavita.plugin.fail2ban.allowlist.ip=::1,127.0.0.1
      - traefik.http.middlewares.fail2ban-kavita.plugin.fail2ban.rules.bantime=10m
      - traefik.http.middlewares.fail2ban-kavita.plugin.fail2ban.rules.enabled=true
      - traefik.http.middlewares.fail2ban-kavita.plugin.fail2ban.rules.findtime=10m
      - traefik.http.middlewares.fail2ban-kavita.plugin.fail2ban.rules.maxretry=4
      - traefik.http.middlewares.fail2ban-kavita.plugin.fail2ban.rules.statuscode=401
      - traefik.http.routers.kavita.middlewares=kavita@docker,fail2ban-kavita@docker
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${GENERIC_TIMEZONE}
    volumes:
      - ${DOCKER_DIR}/kavita/config:/config
      - /mnt/media/data/suwayomi-server/files/local:/data/local
      - /mnt/media/data/suwayomi-server/downloads:/data/downloads
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      - media_infra_net

  # dispatcharr:
  #   image: ghcr.io/dispatcharr/dispatcharr:latest
  #   restart: unless-stopped
  #   container_name: dispatcharr
    # labels:
    #   - homepage.group=Media
    #   - homepage.name=Dispatcharr
    #   - homepage.icon=dispatcharr.svg
    #   - homepage.href=${RASPBERRY_ADDRESS}:9191
    #   - homepage.description=IPTV Management
  #   ports:
  #     - 9191:9191
  #   volumes:
  #     - ${DOCKER_DIR}/dispatcharr/data:/data
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${GENERIC_TIMEZONE}
  #     - DISPATCHARR_ENV=aio
  #     - REDIS_HOST=localhost
  #     - CELERY_BROKER_URL=redis://localhost:6379/0
  #     - DISPATCHARR_LOG_LEVEL=info

networks:
  media_infra_net:
    name: media_infra_net
    driver: bridge
