services:

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    environment: 
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=Zurich
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    labels:
      - homepage.group=Torrent
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent.svg
      - homepage.href=${RASPBERRY_ADDRESS}:8080
      - homepage.description=Torrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${GENERIC_TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${DOCKER_DIR}/qbittorrent/appdata:/config
      - /mnt/media/data/torrents:/data/torrents
    restart: unless-stopped
    network_mode: "service:gluetun"
